uploads = []
generated = []

[[outputs]]
id = "FpIy0t6B2FNI44tw-xspq"
uri = "file://app-debug.apk"
type = "unspecified"
title = "Distancia a Las Malvinas — app-debug.apk"

[[outputs]]
id = "ehiy2p_IiEzxBcX--cx7V"
uri = "file://qr-apk.png"
type = "image"
title = "QR — Descargar APK desde el teléfono"

[[outputs]]
id = "I-cUNrnN1HTZWKq3_5Rpi"
uri = "file://qr-apk-v2.png"
type = "image"
title = "QR — Descargar APK v1.0.1 (con bandera)"

[[outputs]]
id = "WYmMgG-siTdzsKj818Dxu"
uri = "file://qr-apk-v3.png"
type = "image"
title = "QR — Descargar APK v1.0.2"

[[outputs]]
id = "EtZ81IMdnSn5LfuOBGo6U"
uri = "file://qr-apk-v4.png"
type = "image"
title = "QR — Descargar APK v1.0.3"
